### ISSUE TITLE
Option positioning in 'table-cell' like layout

### ISSUE THREAD

**Issue by hajikelist** [lcdsantos/jQuery-Selectric#100]
So one thing most select box libs miss is proper positioning of the option selector. In my experience the only way to do this correctly is to have the options in a container in the body tag, absolutely positioned beneath/above the selector [depending on proximity to window edges]. The alternative is that table cells or flex-box containers cannot contain the selector correctly due to the absolute positioning of the options container not effecting or updating the dom parent with correct dimensions. I'm adding a simple patch to this in my implementation to provide this as an option.

**Comment by gearsdigital** [comment]
I'll close this for now. Maybe we come back to this later...
