### ISSUE TITLE
No HTML markup examples for selects

### ISSUE THREAD

**Issue by wzup** [lcdsantos/jQuery-Selectric#105]
Thank you for plugins. We'd like to use them, but unfortunately you didn't provide HTML markup for examples. Only JS code. Where may we find HTML? 

![jquery selectric - google chrome 2016-02-13 12 49 44](https://cloud.githubusercontent.com/assets/3880497/13025942/964ab8c0-d250-11e5-88e0-9c371c509182.png)

What is `$('select')` element on the screenshot?

**Comment by wzup** [comment]
For now I found one way. To create a classic plain vanilla `<select>` element and call `.selectric()` on it:
```
<select id="elem">
    <option value="1">Mango</option>
    <option value="2">Pineapple</option>
</select>

$('#elem').selectric();
```

But is there more ways to do it?

**Comment by mcaskill** [comment]
The `$('select')` is a jQuery _tag_ selector that retrieves all `<select>` elements.
The `$('#elem')` is a jQuery _ID_ selector that retrieves all `id="elem"` elements.
The `$('select#elem')` is a jQuery _tag+ID_ selector that retrieves all `<select id="elem">` elements.

The Selectric plugin does not feature a auto-magic initializer like Bootstrap has with its data-attributes API (e.g., `data-toggle="modal"`). But you can easily implement such a feature by using something as simple as this in your JS:

```js
$('[data-widget="selectric"]').selectric();
```

```html
<select id="elem" data-widget="selectric">
    <option value="1">Mango</option>
    <option value="2">Pineapple</option>
</select>
```

Which is basically what Bootstrap uses. So, anytime you want a `<select>` to use Selectric, you'd just add that data-attribute to apply it.

**Comment by lcdsantos** [comment]
Your HTML should be any normal, valid, HTML <select> element.

Please refer to [this MDN entry](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) to learn more.
