### ISSUE TITLE
Issue with original select values

### ISSUE THREAD

**Issue by Bobz-zg** [lcdsantos/jQuery-Selectric#106]
Hi there,

I'm trying to use selectric to replace woocommerce select attribute on product page.
But it looks like not behaving well.

I have 2 selects 'Color' and 'Size' and selectric is set $(select).selectric();

So I first select 'Color', and in original select, only selected option remains, and all others are removed from DOM. 
```
<select name="color">
<option value="">Choose an option</option>
<option value="black">Black</option>
</select>
```
Then I select 'Size' and in this one everything is in place in original select ,and all goes well.

Now I wan't to select another color, and I do so, but original <select> don't changes, leaving only first option there, the markup stays as aboe.

Since there is some AJAX which is getting price for selected attribute, this is then breaking it because it needs original select item to get values from.Then I need to select empty value to restore functionality.
I'm not sure why is this happening.

Also, I'm not able to re-init the select back to original.
I have tried 

```$('select').selectric('refresh');```

and then to loop $.each but non of them was returning value to initial 'Choose.. '

BR
V

**Comment by mcaskill** [comment]
Hrm. What does the initialization of Selectric look like on _Color_ and _Size_ ? Can't think of anything that would remove `<option>` elements from the DOM.

So, _Color_ influences the available _Size_ options; is this bi-directional?

**Comment by Bobz-zg** [comment]
Hi,

I just fire ```$('select').selectric();``` so it's fired for all.
If I remove selectric and leave only default selects, then no issues.

I have also checked the woocommerce functions there is nothing there messsing the select, it just fires 'on change'.
