### ISSUE TITLE
Selectric destroy not working

### ISSUE THREAD

**Issue by mohammedshoib** [lcdsantos/jQuery-Selectric#107]
hi, 

I am facing one issue here, when I call 
$('select').selectric('destroy') -> it actually initializes the plugin, if not initialized, this is creating problem for me. As per convention it should destroy no matter what, if it is initialized or not.

Is there any other method, to find out whether plugin is initialized on select?

**Comment by mcaskill** [comment]
Hrm. That's silly for the plugin to initialize itself before triggering the 'destroy' method but it makes sense  considering the other public methods (open, close, refresh, and init).

One way to test if Selectric is already initialized is to use the jQuery Data API. Selectric stores its instance within the `<select>` element.

```
var Selectric = $('select').data('selectric');

if (Selectric) {
	Selectric.destroy();
}
```

Alternatively or in addition to the previous example:

```
var $('.selectric-hide-select select').data('selectric');
```
