### ISSUE TITLE
I can't seems to be able disable options on the fly

### ISSUE THREAD

**Issue by malhayek2014** [lcdsantos/jQuery-Selectric#109]
First, Thank you for a great tool.

I need to be able to make an ajax request before the menu opens to find out which options should be enables/disabled.

When the ajax request succeeded I go over each option and disable it when needed. Unfortunately the option do not get disabled.

Here is my code 

   $('#MasterWrapUps').selectric();

    $('#MasterWrapUps').on('selectric-before-open', function (e) {

        var status = "noattempt";

        $.ajax({
            type: "GET",
            url: "/getStatus",
            dataType: "json",
            cache: false,
            success: function (data) {

                if ( data && ! $.isEmptyObject(data) ) {
                    status = data.status;
                }

                attrWrapUpMenu(status);

            }
        });

    });

    function attrWrapUpMenu(status)
    {
        $('.dispositionMenuOption').each(function (index, element) {

            var option = $(element);

            if ( customIsAllowed(status, option) ) {

                option.attr("disabled", false);

            } else {

                if( option.attr('selected') ) {
                    //At this point we know the option that is select can't be used, select the default value
                    $('#MasterWrapUps').val('0')
                }

                option.attr("disabled", true);
            }

        });
    }

I have also opened a question is [StackOverFlow](http://stackoverflow.com/questions/35752780/how-to-disable-menu-options-before-open-using-jquery-selectric)

Also, how can I get a custom data attribute for the selected item? Here is what I have done which is not working. It is returing null where it should return value

    $('#MasterWrapUps').find(":selected").prop('data-category');

Is this a bug or did I miss something?

**Comment by lcdsantos** [comment]
Try to refresh Selectric after you update the options.
```diff
function attrWrapUpMenu(status)
{
    $('.dispositionMenuOption').each(function (index, element) {

        var option = $(element);

        if ( customIsAllowed(status, option) ) {

            option.attr("disabled", false);

        } else {

            if( option.attr('selected') ) {
                //At this point we know the option that is select can't be used, select the default value
                $('#MasterWrapUps').val('0')
            }

            option.attr("disabled", true);
        }

    });

+    $('#MasterWrapUps').selectric('refresh');
}
```

**Comment by malhayek2014** [comment]
@lcdsantos 

The problem with using refresh is that it closes the menu. Then the ajax will be called again before the next open causing a loop which will prevent the menu from opening.

**Comment by lcdsantos** [comment]
Try this:

```js
$('#MasterWrapUps').selectric('refresh');
$('#MasterWrapUps').selectric('open');
```

**Comment by malhayek2014** [comment]
That did not work either. The $('#MasterWrapUps').selectric('open'); seems to be calling the `selectric-before-open` just before causing the same loop.

Also, what is the right way to get the value of the selected option? I tried $("#MasterWrapUps").val() which return null. Is this the correct way to get the value of the selected option?

**Comment by lcdsantos** [comment]
A really, really hacky way: https://jsfiddle.net/lcdsantos/rgaeqbp6/

**Comment by malhayek2014** [comment]
@lcdsantos Thank you so much! That did the trick! I can't thank you enough for this. I recommend adding a new event to handle this scenario to make it easier for the next person!
