### ISSUE TITLE
Ajax pages not refreshing options

### ISSUE THREAD

**Issue by CHEWX** [lcdsantos/jQuery-Selectric#112]
Hi,

Using selectric with an Ajax architected website. So need to use `selectric('init')` on every page load once the Ajax call has returned.

However, it's not keeping my options from my initail init.

`
{
                    responsive: true,
                    arrowButtonMarkup: '<b class="button"></b>',
                    disableOnMobile: false
}
`

The `'init'` is working, but resetting my options, to the defaults.

Thanks,
Tom

**Comment by lcdsantos** [comment]
Try using `selectric('refresh')`.

Let me know if this works

**Comment by CHEWX** [comment]
Tried both, to no avail.

Currently changed the core to the above settings, but not ideally come `bower update` / `bower install`

**Comment by lcdsantos** [comment]
Are you using the latest version (v1.9.6)?

**Comment by CHEWX** [comment]
Yes.

**Comment by lcdsantos** [comment]
I couldn't reproduce the problem here.

Can you create a reduced test case in [https://jsfiddle.net/](https://jsfiddle.net/)?

**Comment by KennethanCeyer** [comment]
I faced same issue.

I gived disabledOnMobile option.

However that plugin is refreshed,

This option will be ignored.

Please check following link.

https://github.com/lcdsantos/jQuery-Selectric/blob/master/src/jquery.selectric.js#L716

**Comment by KennethanCeyer** [comment]
If you want to refresh selectric element When non-mobile environment.

You have to follow this code (Until now)

```javascript
if ($element.data('selectric').disableOnMobile === true) {
    if ($element.data('selectric').utils.isMobile() !== true) {
        $element.selectric('refresh');
    }
}
else {
    $element.selectric('refresh');
}
```

**Comment by gearsdigital** [comment]
@KennethanCeyer The intention of `disabledOnMobile` is to disable the rendering of markup. It would be awesome if you could clarify your use case a bit for me? What would you expect selectric to do?
