### ISSUE TITLE
I'm not able to close selectbox opened via js

### ISSUE THREAD

**Issue by Dejv92** [lcdsantos/jQuery-Selectric#113]
I have a 'links' near every select on page, every select is selectric. This links should toggle select.

This code does it:

```
$( document ).on('click', '.variants-text', function () {
		var selectricSelectbox = $( this ).next();
		
		if( selectricSelectbox.hasClass( 'selectric-open' ) ){
			selectricSelectbox.find( 'select' ).selectric( 'close' );
		} else {
			selectricSelectbox.find( 'select' ).selectric( 'open' );
		}
	} );
```

It works, but if I open some select, than open another one via link, I'm not able to close this select by clicking somewhere else on document. Another opened select works fine.
I also try this

```
	$( document ).on('click', '.variants-text', function () {
		var selectricSelectbox = $( this ).next();
		
		if( selectricSelectbox.hasClass( 'selectric-open' ) ){
			$( '.selectric-wrapper.selectric-open select' ).selectric( 'close' );
			//selectricSelectbox.find( '.variants-selectbox' ).data('selectric').close();
		} else {
			$( '.selectric-wrapper.selectric-open select' ).selectric( 'close' );
			selectricSelectbox.find( 'select' ).selectric( 'open' );
		}
	} );
```

and some more...

HTML structure:

```
<div class="grid-variants">
	    	
 <div class="variants-text">Toggle link</div>

 <div class="selectric-wrapper selectric-variants-selectbox selectric-selectpicker">

  <div class="selectric-hide-select">
   select element
  </div>
  inner selectric content</div>
</div>
```

EDIT: this fiddle is representing my problem - [http://fiddle.jshell.net/y70b4j4o/](http://fiddle.jshell.net/y70b4j4o/l)
try open last selectric (it is not important if you open it with 'opener' or by clicking on selectric), then open first or second selectric via 'opener' and try to close it clicking somewhere else

**Comment by Dejv92** [comment]
I find a way, there was a problem with events, so I modified my js to:
```
	$( document ).on('click', 'div.variants-text', function ( e ) {
		var selectricSelectbox = $( this ).next();
		e.stopPropagation();
		if( !selectricSelectbox.hasClass( 'selectric-open' ) ){
			selectricSelectbox.find( 'select' ).selectric( 'open' );
		}
	} );
```
question is: Is this a correct solution or should plug-in itself try to handle this situation?

**Comment by lcdsantos** [comment]
You have to use `event.stopPropagation()` on your click so it doesn't conflit with Selectric click event on document.
