### ISSUE TITLE
selectric event for init

### ISSUE THREAD

**Issue by ramlev** [lcdsantos/jQuery-Selectric#116]
When using the selectric-init event, it's fired multiple times.  I need to set all option to default values when initializing the selectric, and if using the -init or -before-open events, it's called even when selecting an option.

My case is that i want to reset selected options on browserback (selectric-init would be nice) so i dont need a onbeforeunload="" in the body tag.

**Comment by gearsdigital** [comment]
@ramlev Sorry that a response took so long! Does your problem still exist?
