### ISSUE TITLE
Nested dropdown on reset

### ISSUE THREAD

**Issue by bewards** [lcdsantos/jQuery-Selectric#117]
I'm using selectric in tandem with knockoutjs. Once the ko viewmodel dropdown is hydrated, I call refresh on all of the selects. I'm noticing that refresh is nesting, inserting the select inside of a nested hide-select wrapper, causing the display label and button to not display. See below's screenshot:

**Before refresh**
![image](https://cloud.githubusercontent.com/assets/3927169/17557916/f2cc7af2-5ee6-11e6-90c4-9a141ffbe295.png)

**After refresh**
![jquery-selectric_nested-bug_2016-08-10_1023](https://cloud.githubusercontent.com/assets/3927169/17557474/59f08284-5ee5-11e6-8e91-1a334be15ef3.png)

Here's my code that inits all selects:
![image](https://cloud.githubusercontent.com/assets/3927169/17557664/171a3d82-5ee6-11e6-9f2b-1f6e25a765e8.png)

Here's the reset call after knockout does its thing:
![image](https://cloud.githubusercontent.com/assets/3927169/17557656/0980f27e-5ee6-11e6-96f0-c43cc08471d2.png)

And here's the markup, just a simple knockout data-bind:
```
<div class="custom-dropdown">
    <select data-bind="options: $root.countries, value: ddSelectedCountry, optionsText: 'displayValue', optionsCaption: 'Select Country'" id="ma_dd_country" name="ma_dd_country"></select>
</div>
```

**Update**
I've reproduced the issue on [jsfiddle](https://jsfiddle.net/sewardsb/k0qcv996/12/). You can comment out the last line in js to see it before the refresh. The markup simply goes through the 2 address objects and populates a country dropdown for each one. I set the first to US and the second to CA (canada) in the mock data.

I noticed that $[first country dropdown].data('selectric') was undefined after going through knockout. Trying to reinitialize both the country dropdowns does not fix the nested issue.

Tested in Chrome (latest) Windows 7.

**Comment by lcdsantos** [comment]
I have no experience with Knockout. But, from what I can see, when the data bindings is applied, the `<select>` element is duplicated inside `.selectric-hide-select`, causing it to create a nested instance of Selectric.

As I possible workaround that I found is to call `selectric('destroy')` method on your selects before applying the data bindinds.

Like this: https://jsfiddle.net/lcdsantos/1stky9y1/1/

Not the best (or the cleanest) solution. But I think it's the only one right now.

**Comment by bewards** [comment]
Thanks @lcdsantos, I'll roll with this option.
