### ISSUE TITLE
Change on hidden select fired even when selection did not change

### ISSUE THREAD

**Issue by muhkuh2005** [lcdsantos/jQuery-Selectric#118]
I just encountered the to me strange behaviour that the change event ist fired on the original select even when the Selectric selection did not change.
(As Example when the viewer clicks on a blank space on the website)

I solved it by the following options:
```javascript
            onBeforeChange: function(select, selectric) {
                $(select).data('currIndex', selectric.state.currValue);
            },
            onChange: function(select, selectric) {
                if($(select).data('currIndex') == selectric.state.currValue)
                    return false;
                $(select).change();
            }
```

But this doesn't feel like the right aproach...

**Comment by Leksat** [comment]
I can confirm the bug exists in v1.10.1

@muhkuh2005 thanks for the workaround!
