### ISSUE TITLE
how to set color for scroll

### ISSUE THREAD

**Issue by neda-sh** [lcdsantos/jQuery-Selectric#119]
hi 
I used jquery-selectric in page and set this code:
           <script>
$(function(){
    $('select').selectric({
        maxHeight: 200
    });
});
</script>
so it put scroll for dropdownlist I want change scroll bar's color for dropdownlist 
How I can do it?
Best regards
neda

**Comment by lcdsantos** [comment]
You can use something like https://css-tricks.com/custom-scrollbars-in-webkit/ (WebKit only).

Or use a jQuery plugin, like:
* https://github.com/malihu/malihu-custom-scrollbar-plugin
* https://github.com/mzubala/jquery-custom-scrollbar
* https://github.com/gromo/jquery.scrollbar
