### ISSUE TITLE
Options shouldn't selected while using the keyboard 

### ISSUE THREAD

**Issue by gearsdigital** [lcdsantos/jQuery-Selectric#121]
While scrolling through the option list (using the up and down arrow keys), items shouldn't get selected. It seems to be a convenient way to select items but it breaks with what a user might expect.

Related to https://github.com/lcdsantos/jQuery-Selectric/pull/120 its not possible to deal with multiple selects. So we should align the keyboard integration on native selects.

1. Pressing Enter/Space selects an item
2. Using Up/Down highlights an item (but does not select it!)

**Comment by lcdsantos** [comment]
I'm not sure what you meant?

It's working like that for me. Up and Down arrows highlights the item but it's only when I press Enter/Esc that the option is seleted. Like a native select.

I'm using Chrome v53 and Firefox v47 on Windows 10.

**Comment by gearsdigital** [comment]
**Given:** a single select, scrolling through `selectric-items` using up/down arrow keys. If a `li` is getting the `selected` class, the related`option` is selected too. And that is the point! I think it shouldn't be selected until the user actively decides too (click, space, enter).

![current 1](https://cloud.githubusercontent.com/assets/965069/18687979/c418a35e-7f82-11e6-9f84-e6c397d43c48.gif)

What I've done: I scrolled a bit up/down and stopped my scrolling on `Bird`. Then i pressed `ESC`. I'ld expect nothing to be selected. But if I press submit `Bird` was sent to the server.

Okay, playing a bit around, I know why you're (and me) confused. Your described behaviour is true for Chrome and Firefox under Windows. I got the same result on Firefox Mac. Chrome and Safari, both Mac, are working slightly different.

![chrome](https://cloud.githubusercontent.com/assets/965069/18688314/0bf329e6-7f84-11e6-8f09-ecb260a8b23d.gif)

**The other point:** What would you do using multiple selects? Not sure what is the beste way here. Using the current implementation it'll not work.

**Comment by lcdsantos** [comment]
Hey @gearsdigital, I've made a few changes. Could you take a look? It's on [multile branch](/lcdsantos/jQuery-Selectric/tree/multiple).

**Comment by gearsdigital** [comment]
@lcdsantos Sure thing. I'll take a look.
