### ISSUE TITLE
Apply hooks locally

### ISSUE THREAD

**Issue by gearsdigital** [lcdsantos/jQuery-Selectric#134]
Hooksare currently applied globally. If I write something like that `$.fn.selectric.hooks.add('Init', 'placeholder', setPlaceholder);` all other selectric instances are affected.

Wouldn't it be better to allow hooks to be applied per instance? What was the original thought to implement this function? The Event-System is relatively similar, isn't it?

```js
const select = $('select').selectric();
const hooks = select.selectric('hooks');

hooks.add('Init', 'placeholder', setPlaceholder);
```

#140

**Comment by lcdsantos** [comment]
The idea was to implement modules/plugins to Selectric and expand it's functionality, like [this](https://github.com/lcdsantos/jQuery-Selectric/blob/gh-pages/plugins/jquery.selectric.placeholder.js).

To be honest, I don't even know if this is still working.

**Comment by gearsdigital** [comment]
The Hook-System is still working, but only globally for all instances. Your mentioned functionality is possible today using events.

I'm pretty sure removing the hook system would improve the usability and reduce the plugin complexity overall. It does not makes much sense to have several ways to do the same job.

What do you think?

### Example using events

```js
$('.fixed-label').on('selectric-init selectric-change', setPlaceholder);

function setPlaceholder(event, element, data) {
    const select = $(element);
    const placeholder = select.attr('data-placeholder');
    const wrapper = select.closest(`.${data.classes.wrapper}`);
    const label = wrapper.find('.label');

    if ( label.text() !== placeholder ) {
        label.text(placeholder);
    }
}
```

**Comment by lcdsantos** [comment]
Yeah, I think events will do just fine :)

**Comment by gearsdigital** [comment]
If you want I can remove the hook-stuff… Have some spare time right now :)

**Comment by lcdsantos** [comment]
Sure 👍

**Comment by laphilosophia** [comment]
here. fixed it.

`$(selector).selectric({
    maxHeight: 450,
    onInit: function(element, obj) {
      var select = $(element);
      var placeholder = select.data('placeholder');
      var wrapper = select.closest('.selectric-wrapper');
      var label = wrapper.find('.label');
      if ( label.text() !== placeholder ) {
        label.text(placeholder);
      }
    }
  });`

**Comment by 1v** [comment]
Equivalent of hook, as I think:
```javascript
$(document).on('selectric-init', 'select', function(event, element, data) {});
```
