### ISSUE TITLE
CSS Theme breaks typing in list with Chrome

### ISSUE THREAD

**Issue by ymercille** [lcdsantos/jQuery-Selectric#141]
It's impossible to use the keyboard to type in the list when using Chrome browser. Normally, if we type the first letter, it will moves the focus to the first item having that letter in the list.

After some test on my side, I finally discovered that something in the stylesheet of selectric break this standard behavior only in special themes. We can reproduce the issue by going to demo page http://selectric.js.org/demo.html. When using the default theme, all is working well, but when choosing any other theme, it breaks the use of the keyboard, 

Thank you.

**Comment by gearsdigital** [comment]
@ymercille, we have not really an issue here. There was recently a minor update ([1.11.0](https://github.com/lcdsantos/jQuery-Selectric/releases)) which changed the way how elements are highlighted. Take a look at this [commit](https://github.com/lcdsantos/jQuery-Selectric/pull/123/commits/c78b153cb5a46cd633a5060d6a8e91c4f6fde8ac#diff-fad3024d63edb6c273a83de28f23aa4aR880).

I've checked the demo and can confirm that the highlighting is not working as expected. But it is working technically! We miss only some lines of css...

As a simple workaround just add the following rules to your css and change it to your needs. Pretty sure there will be an update as soon as possible. If you are interested, you could provide a pull request :)

```css
.highlighted {
  background: grey;
  color: white;
}
``

**Comment by lcdsantos** [comment]
I've updated the themes on demo page to reflect the latest changes.
