### ISSUE TITLE
Why do we have two arrays with similar data?

### ISSUE THREAD

**Issue by gearsdigital** [lcdsantos/jQuery-Selectric#142]
[`items`](https://github.com/lcdsantos/jQuery-Selectric/blob/master/src/jquery.selectric.js#L419) and [`lookupItems`](https://github.com/lcdsantos/jQuery-Selectric/blob/master/src/jquery.selectric.js#L420) are equal and I wonder why we have two arrays containing similar data? In order to reduce code complexity, it would be nice (_if there is no relevant reason_) to unify this and just go with one of both.

```js
items:Array[28]
lookupItems:Array[28]
```

**Comment by lcdsantos** [comment]
Because `optgroup`.

Every `optgroup` creates a nested items array, `lookupItems` is a flattened version of that so we can iterate over each item.

**Comment by gearsdigital** [comment]
Ah, okay. Thanks for clarification… :)
