### ISSUE TITLE
[BUG Report] z-index problem

### ISSUE THREAD

**Issue by gabrieltva** [lcdsantos/jQuery-Selectric#143]
Hi guys,

I have a problem here! When I open the selectric, all the options is in back on the content. I apply z-index with value "99999" in all the div of the selectric, but nothing change.

See the print:
![captura de tela 2016-10-10 as 16 36 56](https://cloud.githubusercontent.com/assets/5474849/19248675/d14f11e0-8f07-11e6-8325-63b8cab20f5b.png)

Can you help?

**Comment by gearsdigital** [comment]
Hi @gabrieltva, could you provide a minimal and verifiable example? Maybe a [jsbin](http://jsbin.com) or [jsfiddle](https://jsfiddle.net).

Were do you have applied your z-index value? `.selectric-wrapper`?

**Comment by gabrieltva** [comment]
Hi, thanks for your help!

I found the problem! Is a conflict with this css code:
```
.no-touch * {
    -webkit-transform: translate3d(0,0,0);
    -moz-transform: translate3d(0,0,0);
    -ms-transform: translate3d(0,0,0);
    -o-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
}
```

Thanks again, and sorry for the issue!

**Comment by lcdsantos** [comment]
Hey @gabrieltva, just for the record: a transform property will create a [stacking context](new stacking context).

Are you applying these `translate3d` to make it hardware accelerated? You could use [`will-change`](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) or something like `background-visibility: hidden;`.

**Comment by gabrieltva** [comment]
Hi @lcdsantos, yes. I'm using the translate3d to hardware accelerated. But I fixed this ignoring the Selectric div's. Like this:

```
.no-touch .selectric-wrapper {
    -webkit-transform: initial;
    -moz-transform: initial;
    -ms-transform: initial;
    -o-transform: initial;
    transform: initial;
}
```

But, anyway. Thanks for your help! =)
