### ISSUE TITLE
Problems with Contact Form 7

### ISSUE THREAD

**Issue by tmconnect** [lcdsantos/jQuery-Selectric#145]
Hello,

I'm using Selectric with WordPress Contact Form 7 plugin and try to make a multiple select field in CF7.

If I select more than one item the select label entries are empty. I take a look at inspector and see that the `<span class="label"></span>` has no content, if multiple options selected. If only one item is selected, it has the entry of the selected item: `<span class="label">Dagobert Duck</span>`.

The `selectric-items` looks correct no matter whether one item or multiple items are selected:

```
<div class="selectric-items" tabindex="-1" style="width: 1140px;">
    <div class="selectric-scroll">
        <ul>
            <li data-index="0" class="selected">Dagobert Duck</li>
            <li data-index="1" class="selected">Donald Duck</li>
            <li data-index="2" class="">Micky Mouse</li>
        </ul>
    </div>
</div>
```

If I put a hard coded select element to the page, it's working correct.

I can't figure out, what's the problem within the CF7 form. Here's the part of the code generated from CF7 for the select element before any selections are made. The code differs only minimally in the classes to the normal select field on the `selectric-wrapper` div. 

```
<div class="selectric-wrapper selectric-wpcf7-form-control selectric-wpcf7-select selectric-open">
    <div class="selectric-hide-select">
        <select name="auswahl[]" class="wpcf7-form-control wpcf7-select" id="basics" aria-invalid="false" multiple="multiple" tabindex="0" style="">
            <option value="Dagobert Duck">Dagobert Duck</option>
            <option value="Donald Duck">Donald Duck</option>
            <option value="Micky Mouse">Micky Mouse</option>
        </select>
    </div>
    <div class="selectric">
        <span class="label">Dagobert Duck</span>
        <b class="button">▾</b>
    </div>
    <div class="selectric-items" tabindex="-1" style="width: 1140px;">
        <div class="selectric-scroll">
            <ul>
                <li data-index="0" class="">Dagobert Duck</li>
                <li data-index="1" class="">Donald Duck</li>
                <li data-index="2" class="">Micky Mouse</li>
            </ul>
        </div>
    </div>
    <input class="selectric-input" tabindex="0">
</div>

Any idea what's happing?

Thanks
Thomas
```

**Comment by gearsdigital** [comment]
Hey Thomas,

so far the generated markup looks good to me. Could you please provide some informations about your selectric version and your browser version? And could you please provide your releated selectric config?

**Comment by tmconnect** [comment]
Thanks for your quick replay.

First I want to answer your questions:
Selectric v1.11.0
Safari 10.0
Selectric config is very simple
```
$('select').selectric({
	disableOnMobile		: false
});
```

After my first post I still testing my code a few times and figured out, that is has something to do with the case of the values. It's strange, but when I change the values to lowercase, it works as expected.

So, I do not think it has anything to do with the version, the browser or the Selectric config.

Now, I know how to handle my contact form - but I hope this info would be helpful to improve your plugin.

Cheers
Thomas

**Comment by gearsdigital** [comment]
Thank you for your feedback Thomas! I was able to reproduce your issue and guess what: You found a solid bug 👍

While `<option value="Dagobert Duck">Dagobert Duck</option>` is not working `<option value="DagobertDuck">Dagobert Duck</option>` will. So the problem is not case related but whitespace. I'll fix that and let you know :)

Thanks for reporting!

**Comment by tmconnect** [comment]
It is probably both. For me `<option value="DagobertDuck">Dagobert Duck</option>` **and** `<option value="dagobert duck">Dagobert Duck</option>` (with blank but lowercase) works.

**Comment by gearsdigital** [comment]
You're right! Somehow strange... Thanks again!

**Comment by gearsdigital** [comment]
The Bug was located in `labelBuilder` which prevented the label to be build correctly although form state was fine. Selected items are sent to the server but not visually highlighted. 

I've fixed that issue now. If you want to use this version just download the new version directly from master. We'll ship a new version later this year.
