### ISSUE TITLE
Multiple select label empty when multiple selected

### ISSUE THREAD

**Issue by damienmcd** [lcdsantos/jQuery-Selectric#149]
I can see the label updating when I select one in a multiple select list, however, when I select more than one item the label is emptied.
See screenshots attached:
https://www.evernote.com/shard/s31/sh/6831ca07-27ed-45b9-9197-62dc45fcdea7/c512827624a080748ff4e32c214e48d8

Is there anything I can do to fix the labelling when multiple items are selected?

Thanks,
Damien

**Comment by gearsdigital** [comment]
Damien, thank you for reporting the issue!

Are you able to provide a fiddle to reproduce your issue? All tests are running fine and the 
demo is working as expected :/

**Comment by damienmcd** [comment]
I've a fiddle set up here showing the same result:
https://jsfiddle.net/damienmcd/v4tm3170/29/

**Comment by damienmcd** [comment]
Is there somewhere I need to specify in the selectric init that it will be a muliple select?
I've tried adding the options below but they have not fixed the issue:
  multiple: {
    separator: ', ',       // Type: String.             Description: Items separator.
    keepMenuOpen: true,    // Type: Boolean.            Description: Close after an item is selected.
    maxLabelEntries: false // Type: Boolean or Integer. Description: Max selected items do show.
  }

**Comment by gearsdigital** [comment]
Thank you @damienmcd. What we've got here is a [known issue](https://github.com/lcdsantos/jQuery-Selectric/issues/145#issuecomment-254334292) which will be fixed soon.

**Comment by damienmcd** [comment]
Thanks for that.
Setting the option values to lowercase as mentioned in the referenced known issue works.
