### ISSUE TITLE
Many events not triggered in mobile mode

### ISSUE THREAD

**Issue by webbson** [lcdsantos/jQuery-Selectric#151]
The events I've identified to not trigger in mobile mode are all the following ones bound in selectric. 

```
var $select = $('select');
$select.selectric({
	onBeforeOpen: function () {
		console.log('beforeopen');
	},
	onOpen: function () {
		console.log('open');
	},
	onClose: function () {
		console.log('close');
	},
	onBeforeClose: function() {
		console.log('beforeclose')
	},
	onBeforeChange: function () {
		console.log('change')
	},
	onChange: function () {
		console.log('change')
	},
	onSelect: function () {
		console.log('select')
	},
	onBeforeSelect: function () {
		console.log('beforeselect')
	},
});
$select.on('change', function () {
	console.log('Native change event');
});
```

**Comment by gearsdigital** [comment]
@webbson Thank you for reporting this issue!

Could please add some details about your mobile device/os? Android, iOS or something else?

**Comment by webbson** [comment]
I have reproduced it on both iOS, Android as well as Chrome's device emulator mode set to iPhone (might be on others as well, as long as they trigger the native mobile dropdown).

**Comment by gearsdigital** [comment]
Okay, let me explain what is going on:

Some of the events you mentioned are bound only to generated markup (`onOpen` for example). You can enable the rendering by setting `disableOnMobile` to `false`. This will bind all releated events too.

The change event is a bit tricky here. Mobile UA fireing the change event not after an option was selected but right after the dropdown element was closed. Thats why `onSelect` does not work as you might expect.

I'll close this issue for now. Feel free to reopen.
