### ISSUE TITLE
Disabled is ignored for sub-options

### ISSUE THREAD

**Issue by tj-shapeways** [lcdsantos/jQuery-Selectric#152]
Option within optgroup is never given disabled class if the optgroup is not disabled and the option has disabled. [See Fiddle.](https://jsfiddle.net/w9e68r60/1/) Option 2.1 is disabled but still selectable.

It looks like the change could be made on the line below to look for the disabled prop on the $elm or optionsGroup.groupDisabled.

`optionsGroup.items[i] = _this.getItemData(currIndex, $elm, optionsGroup.groupDisabled);`

**Comment by gearsdigital** [comment]
Howdy @tj-shapeways 

Thank you for reporting this issue! I'll take look…

**Comment by tj-shapeways** [comment]
It looks like this or similar logic will fix this bug: 

`optionsGroup.items[i] = _this.getItemData(currIndex, $elm, optionsGroup.groupDisabled || $elm.prop('disabled'));`
