### ISSUE TITLE
How to use with browserify?

### ISSUE THREAD

**Issue by franszo** [lcdsantos/jQuery-Selectric#155]
Hi there, culd you please help me out, how to use this with browserify?

Im using 

global.jQuery = require('jquery');
var selectric =	require('selectric');

jQuery('select').selectric();

but always having an error selectric is not a function

**Comment by lcdsantos** [comment]
Try passing jQuery as a parameter, like this:

```js
global.jQuery = require('jquery');
var selectric = require('selectric')(jQuery);

jQuery('select').selectric();
```

**Comment by franszo** [comment]
You are a life saver sir! many thanks

**Comment by marcbelletre** [comment]
I'm having the same issue trying to use this plugin as a node module. I would like to import it like I do with other plugins like this:
`const selectric = require('selectric');`

Unfortunately @lcdsantos's solution is not working for me and returns the following error in Chrome inspector:
> Uncaught TypeError: \_\_webpack_require\_\_(...) is not a function

Does anyone here managed to make it work like this?
Thanks!
