### ISSUE TITLE
Selectric menu doesn't show styles on mobile

### ISSUE THREAD

**Issue by tfadz27** [lcdsantos/jQuery-Selectric#159]
I'm not sure what i'm doing wrong but when I view my select dropdown on mobile it removes all my css styles and just shows a generic select dropdown. I would think the styles would be defaulted for mobile. Can anyone tell me why it's not showing it styled on mobile?

Here is a screenshot of what I'm seeing.
https://www.evernote.com/l/ArHNq-dUJy5AhK1GmaXaMsYLD_hqvhhTIII

Thanks

**Comment by tj-shapeways** [comment]
At this time Selectric defaults to not rendering on mobile, and therefore does not add the classes that your css expects. If you would like to render Selectric on mobile, change the following options when initializing: 
```  
    /*
     * Type: Boolean
     * Description: Initialize plugin on mobile browsers
     */
    disableOnMobile: true,

    /*
     * Type: Boolean
     * Description: Retain native dropdown behavior on mobile devices
     */
     nativeOnMobile: true,
```

More information can be found here: http://selectric.js.org/

**Comment by tfadz27** [comment]
Thanks but it's still not showing right.This is exactly what I have and it's not showing any different on mobile.

  $('.aoc-select-dropdown').selectric({
    maxHeight: 800,
    nativeOnMobile: true,
    disableOnMobile: true
  });

**Comment by tj-shapeways** [comment]
Try: 

```
$('.aoc-select-dropdown').selectric({
maxHeight: 800,
nativeOnMobile: false,
disableOnMobile: false
});
```

**Comment by tfadz27** [comment]
Thanks you it's showing up correctly now :)
