### ISSUE TITLE
Wrong version provided via bower

### ISSUE THREAD

**Issue by cristiancalara** [lcdsantos/jQuery-Selectric#163]
It seems that the latest release tag do not have the files in the public folder updated. They still show v1.10.1

See
- https://github.com/lcdsantos/jQuery-Selectric/commit/aeca59d350285356394b00a868f231a955b9b050 
- https://github.com/lcdsantos/jQuery-Selectric/blob/aeca59d350285356394b00a868f231a955b9b050/public/jquery.selectric.js

**Comment by lcdsantos** [comment]
It should be working now. Can you confirm, please?

Current version should be v1.11.1.

**Comment by cristiancalara** [comment]
Yes, this is now working. 

Thanks.
