### ISSUE TITLE
doesn't work selectric in mobile 

### ISSUE THREAD

**Issue by kselax** [lcdsantos/jQuery-Selectric#176]
Hello! I have problem , all work good in full display and when I go to mobile it doesn't work, Items don't choose.
this page with selectric http://aksioma.lesqa.com/?post_type=blog , in mobile not work 

when I choose any item and I don't go to page, http://prntscr.com/esgyyb . 
this page where selectric called http://aksioma.lesqa.com/wp-content/themes/oxioma/js/pages/page_smi_mnogo.js?ver=4.7.3
Why this happen ???

**Comment by tj-shapeways** [comment]
Please set the following options to enable selectric on mobile:

```
$el.selectric({
  disableOnMobile: false,
  nativeOnMobile: false
});
```

along with any other options you may be using.

**Comment by kselax** [comment]
Thanks!, all work good.

**Comment by JFusco** [comment]
I think this should be re-opened. The native select doesn't work with selectric, which is why this was originally opened. You are setting the nativeOnMobile to false, which is ignoring the issue that it doesn't work on a native device.

**Comment by ProjectINT** [comment]
tj-shapeways Thanks it's work for me too

**Comment by zetu** [comment]
If you want **nativeOnMobile** to be **true** then you have to change CSS for **select**:
```
width: inherit !important;
height: inherit !important;
clip: inherit !important;
```
