### ISSUE TITLE
Selectric onChange event does not fire on iOS9

### ISSUE THREAD

**Issue by dominikkremerio** [lcdsantos/jQuery-Selectric#177]
Hey guys,

I just stumbled across this and wanted to let you know.

The `onChange` callback function does not fire when I select a different option on iOS9.
As workaround it is possible to set the `nativeOnMobile: false` option.

Here is a demo: https://codepen.io/anon/pen/NjWeYm
```
$('select').selectric({
  onChange: function (element) {
    alert('onChange')
  },
  // nativeOnMobile: false
})
```

I guess the problem is that iOS does not fire the `change` event on selecting a new option rather than `blur`.

**Comment by gearsdigital** [comment]
Thank you for reporting this issue. We'll take a look...

**Comment by gearsdigital** [comment]
I'm able to verify your issue. But as you mentioned correctly iOS does not fire the `change` event on selecting a new option.

When the user first touches the <select> control, iOS opens a native UI for the select options. This is not DOM. And when the user touches "Done" it sends the new value/index and fires the corresponding event back on DOM (http://stackoverflow.com/a/24056865/294076)

There are some workarounds but I'm not sure what would the best way to fix this. Maybe @lcdsantos  has some ideas?

For now I'll close this issue. Feel free to reopen if needed.

**Comment by dominikkremerio** [comment]
Thanks!
