### ISSUE TITLE
highlighted class on hover li

### ISSUE THREAD

**Issue by Mushr0000m** [lcdsantos/jQuery-Selectric#181]
Hi,
Currently the `highlighted` class is added when using the keyboard but not the mouse hovering an li. The problem is that you can't have a style for selected element and or highlighted/hovered element. Only because when opening it add `highlighted`to the first item that is also `highlighted`.

It would be nice if the class `highlighted` was added only when the user uses the keyboard to navigate OR on mouse hover. Would it be possible ?

Thanks

**Comment by gearsdigital** [comment]
If I understand you correctly you're able to have a styles for selected element and/or highlighted/hovered elements.

```css
.selected {}
.selected.highlighted {}

.selected:hover {}
.selected.highlighted:hover {}

```
https://jsfiddle.net/fLj0zw8a/
