### ISSUE TITLE
Change value without resetting whole selectric box

### ISSUE THREAD

**Issue by soanvig** [lcdsantos/jQuery-Selectric#182]
I use **mCustomScrollbar** plugin inside Selectric, to create scrollable options dropdown.
It works great.

After updating programatically select's value through JS, I need to call `Selectric.refresh()` to update it to correct value.

Here the problem appears:
After doing .refresh it seems, that whole .selectric-scroll is rebuilt, which removes all scrollbar elements created by mCustomScrollbar. Therefore scroll doesn't work and everything works and looks bad.

Of course I could rebuild mCustomScrollbar after each .refresh, but it doesn't work that way.
It doesn't work that way because mCustomScrollbar won't create itself again, and at the same time I cannot destroy it, because it cannot detect its elements (they got destroyed by .refresh).

Is there a way to update the value of Selectric without rebuilding HTML?

EDIT:
I found workaround, by binding mCustomScrollbar to .selectric-items, not .selectric-scroll. This way I can destroy it, and recreate. However the issue is still valid.

**Comment by gearsdigital** [comment]
Thank you for reporting @soanvig!

The current implementation of `refresh()` reconstructs the whole options list. This is why your bound plugin gets destroyed. So there is no built in way to programmatically updating a value.

A simple way to solve your issue would be to stick with the generated markup. Find the item you want to make selected and trigger a click event.

For example:

```js
$('li:last').trigger('click');
```

This will force the dropdown to update the label and all necessary events and callbacks. Of course there are some pitfalls. This will not work if you set `disableOnMobile` or `nativeOnMobile`.

Maybe we'll add a method in the future which adds an api for that. For now i'll close this issue as you found a workaround by yourself.
