### ISSUE TITLE
Force Render Options Box

### ISSUE THREAD

**Issue by kirillminiaev** [lcdsantos/jQuery-Selectric#197]
I see an option that allows the options box to render above. Is there a way to disable this rendering and ONLY allow it to render below (even if it is outside of the visible window scope?

**Comment by SassNinja** [comment]
@kirillminiaev you're lucky: I 've just made a PR that adds such an option https://github.com/lcdsantos/jQuery-Selectric/pull/202

Once it has been accepted & merged you can use `forceRenderBelow: true` for the desired behavior.

**Comment by kirillminiaev** [comment]
@SassNinja wonderful! How will I know when the PR is accepted?
