### ISSUE TITLE
How to require or import the library with ES6/Webpack?

### ISSUE THREAD

**Issue by mCIN4R** [lcdsantos/jQuery-Selectric#227]
Hi Guys,

How can we import this library with Webpack?

I have tried everything I can, but it didn't work. I got every time "not a function" error in the console.

See below what I already have tried;

1. import * as selectric from 'selectric';
2. const selectric = require('selectric');
3. import 'selectric';
4. import selectric from 'selectric';
5. import 'selectric/src/jquery.selectric';
6. import 'selectric/src/jquery.selectric.js';

and calling with;

$('select').selectric();

P.S: jQuery is already defined with $ sign.

Thanks!

**Comment by lcdsantos** [comment]
This should be enough:
```js
import $ from 'jquery';
import 'selectric';

$(function() {
  $('select').selectric();
});
```

Import jQuery before Selectric.

If you're not installing jQuery with npm (or yarn, or whatever...), add as external module in `webpack.config.js`.

```js
// ...
externals: {
    jquery: 'jQuery'
},
plugins: [
    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
    })
]
// ...
```

**Comment by northwood-dev** [comment]
And if you installed the package via npm, you can add the selectric css using SCSS in your project like this :
```
@import "~selectric/public/selectric.css";
```

**Comment by hamed8993** [comment]
i have a node.js project.
i installed both JQuery and selectric npm packages in my project (locally by >npm i ....).
i wrote the selectric codes like bellow, in main.js file.
(directory of main.js file:  my-root-folder\public\js\main.js ).
the codes for import and use of selectric in main.js file:

`import $ from 'jquery';`
`import 'selectric';`
`window.addEventListener("DOMContentLoaded", function(){`
  `  $('select').selectric({`
     `   forceRenderBelow: true`
 `   });`
`  });`
`(function($) {`
 `   'use strict';`
 `   jQuery(document).ready(function($) {`
 `       $('select').selectric({`
 `           forceRenderBelow: true`
  `      });   `               
  `  });`
`})(jQuery);`

but i catch this error in console:
Uncaught SyntaxError: Cannot use import statement outside a module (at main.js:4:1).

the constructor of my project:
root-folder
|
-------------/server.js
-------------/app
-------------------/ other directories like http ,...
-------------------/index.js
-------------/config
-------------/node-modules
------------ /public
---------------------/js/main.js
------------ /resource

these are so many other files. but it is overall schema.
