### ISSUE TITLE
Form validation on select fields that have been selectricfied

### ISSUE THREAD

**Issue by diablodrew** [lcdsantos/jQuery-Selectric#37]
Any recommendations?  I've tried using jQuery-Validation-Engine here:
https://github.com/posabsolute/jQuery-Validation-Engine

and this:

https://github.com/jzaefferer/jquery-validation

Though it looks like since selectric "converts" the drop down list to an unordered list, anything that is trying to validate the form input in real time is going to fail.

Should I just go with a custom post-submit validator? 

Thanks!

**Comment by promptdev** [comment]
Hey @lcdsantos,
I'm finding it hard to make this work with jquery-validation https://github.com/jquery-validation/jquery-validation, selectric seems to be ignoring errors.

errorPlacement seems that is now deprecated
