### ISSUE TITLE
<optgroup> is not supported

### ISSUE THREAD

**Issue by catc** [lcdsantos/jQuery-Selectric#44]
The plugin doesn't support the `<optgroup>` tag. So something like:

```html
<select>
  <optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select>
```

produces an empty select box.

**Comment by damienborgniet** [comment]
Anyone need to use it with optgroup ?

**Comment by catc** [comment]
I've had a few cases where I needed optgroup for organizational purposes. I had to resort to setting an option as disabled (ie: `<option disabled>Group title</option>`) and then styling it as a group header.

**Comment by damienborgniet** [comment]
Tanks a lot !

Le samedi 24 janvier 2015, Catalin Covic <notifications@github.com> a
écrit :

**Comment by jonazu** [comment]
I would be very thankful if optgroup is supported.

**Comment by 2wodigits** [comment]
yeah we need optgroup support please!!
