### ISSUE TITLE
How to close Select A when opening Select B?

### ISSUE THREAD

**Issue by oshihirii** [lcdsantos/jQuery-Selectric#66]
It looks like this behavior should be standard as the code states it with things like:

    // Find any other opened instances of select and close it
    $('.' + _this.classes.hideselect, '.' + _this.classes.open).children()[pluginName]('close');

https://github.com/lcdsantos/jQuery-Selectric/blob/master/dist/jquery.selectric.js#L358

But for whatever reason (perhaps custom css in my implementation) this is not working for me - Select A stays open when opening Select B.  

I can close it via jQuery and CSS with something like:

    $('.customSelectric1_Wrapper').removeClass('customSelectric1_Open');

But then I have to click Select A twice to open again.  

It seems like the plugin is toggling the class or something, perhaps around:

https://github.com/lcdsantos/jQuery-Selectric/blob/master/dist/jquery.selectric.js#L223

Any help on how to force desired behaviour appreciated.

Thank You.

**Comment by lcdsantos** [comment]
Couldn't reproduce this problem here.
Can you make a [jsfiddle](http://jsfiddle.net/) example, with your code so I can look?

(sorry for the long delay)

**Comment by elfguy** [comment]
A click on the select box and the A and B by clicking the select box Select the box in the open A select box when the event is closed, the B onClose select box does not occur at the same time onClose event occurs.

$('select').each(function(){
                $(this).selectric({
                    onOpen: function () {
                        console.log('open');
                    },
                    onChange: function () {
                        console.log('change');
                    },
                    onClose: function () {
                        console.log('close');
                    }
                })
            });
