### ISSUE TITLE
Is it possible to change the selected value from JS code?

### ISSUE THREAD

**Issue by gabor-farkas** [lcdsantos/jQuery-Selectric#69]
The only solution I found currently is to destroy selectric so that things get back to a simple select, then jquery.val(..) works, then I reinit selectric.
Thanks

**Comment by eberon** [comment]
$(element).selectric('refresh') doesn't work?

**Comment by lcdsantos** [comment]
```js
$(element).prop('selectedIndex', index).selectric('refresh');
```

**Comment by gabor-farkas** [comment]
```$(element).val(newValue).selectric('refresh');``` didn't work.
Now I'm doing ```$(element).selectric('destroy').val(newValue).selectric()```. Thanks for the alternative with selectedIndex.

**Comment by enepomnyaschih** [comment]
Here's a workaround I've got to add to handle "change" event properly:

    el.selectric();
    el.change(function() {
        var selectric = el.data('selectric');
        var whatIsSelected = el.val();
        var whatSelectricThinks = selectric.lookupItems[selectric.state.currValue].value;
        if (whatIsSelected !== whatSelectricThinks) {
            el.selectric('destroy').selectric();
        }
    });

It makes the next kind of binding possible:

    el.val('Hello').change();

Blunder that selectric doesn't do it automatically.
