### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by codegrrrl** [lcdsantos/jQuery-Selectric#71]
Hi,

On a recent project I was required to add a few usability tweaks to more closely mimic a standard select box.  I wanted to share these with you in case you felt they were worthy of inclusion in future selectric releases.  Note that I've primarily only tested on Chrome (my project runs on a kiosk and I have control over the browser used).  The issues I ran into:

- when the select box is closed but has focus (eg: you have clicked to open the select box but then pressed escape), there was no visible indicator that focus remained on the select box.  I made changes to apply a "focus" class (see .selectric.focus in the CSS file) so that it could be styled to match inputs with focus.

- when the select box has focus but is closed, I needed it to open the select box upon keyboard input/arrow keys.

- clicking on an item returns focus to the page body instead of maintaining focus on the select box, I needed a user to be able to click an item and then tab to the next input.

You'll find my code changes here:
http://jsfiddle.net/codegrrrl/5zmp1yfa/1/

Code changes are between lines 223 and 300 and are surrounded with comments (note that it is a slightly older version of selectric than your current).

Thank you for such a great plugin, I use it in every project I work on!

**Comment by codegrrrl** [comment]
One more change added at 206 to maintain focus when clicking the selectric label to close the box.
http://jsfiddle.net/codegrrrl/5zmp1yfa/2/

**Comment by eberon** [comment]
Nice! I'm not the author but if this tests well I would like to see it included. I recently did some of my own testing using a variety of screen readers and I wasn't terribly thrilled with the results.
