### ISSUE TITLE
There should be option to not create text search input on plugin init

### ISSUE THREAD

**Issue by DominikSerafin** [lcdsantos/jQuery-Selectric#73]
Just like in the title. Why create unused (most of the time) DOM element which we must hide using css?

**Comment by lcdsantos** [comment]
The hidden input is to catch all keypress/focus/blur events. This was the most 'cross browser' way I found, since I was having trouble to get proper handling on the events across all browsers I tested.

But, I may have a look at this again, and see if I can come up with a better solution.
