### ISSUE TITLE
Not working on tablets

### ISSUE THREAD

**Issue by mohammedshoib** [lcdsantos/jQuery-Selectric#75]
Hi, I am trying use this library on galaxy tablet, but selectric is not working there. Is it the issue or functionality not implemented. I am using chrome emulator to test. 

Thanks.

**Comment by stevepeh** [comment]
Hi, there is a property in the sourcecode:

disableOnMobile: false

set it to false should be ok.

**Comment by mohammedshoib** [comment]
Hi steve,

Thank you very much, you saved lot of my work. Small feedback, I did not
find this functionality on your demo page, I guess you need to put or
explain about all configuration of the library somewhere on the page. May
be it is their on the page if so let me know, so that I can forward that
link to my teammates to refer.

Thanks&Regards
Shoib Mohammed A ( +91-9916330551 )
*Web Developer*
*http://momeen.com <http://momeen.com>*
*http://github.com/mohammedshoib <http://github.com/mohammedshoib>*

**Comment by stevepeh** [comment]
Hi Thanks Shoib
I am not the creator. Just happen to found this library and implement it today as well.
Some times we have to debug ourselves as developers.

**Comment by lcdsantos** [comment]
You can find all available options at projects home: http://lcdsantos.github.io/jQuery-Selectric/
Or Github readme: https://github.com/lcdsantos/jQuery-Selectric

**Comment by mohammedshoib** [comment]
Hi Steve,

It is awesome and use full library.

Thanks&Regards
Shoib Mohammed A ( +91-9916330551 )
*Web Developer*
*http://momeen.com <http://momeen.com>*
*http://github.com/mohammedshoib <http://github.com/mohammedshoib>*
