### ISSUE TITLE
No support for "multiple" attribute

### ISSUE THREAD

**Issue by thekrotek** [lcdsantos/jQuery-Selectric#80]
Looks nice, but "multiple attribute is not supported, which is very frustrating.

**Comment by manuelbieh** [comment]
:+1:

**Comment by DanyDoi** [comment]
+1 :+1:

**Comment by bmazurek** [comment]
+1

**Comment by mattfiocca** [comment]
+1

**Comment by stevepiron** [comment]
+1

**Comment by wekii** [comment]
+1

**Comment by gearsdigital** [comment]
I 'm just about to implement this feature. The current state is very rudimentary and before I move on, I would like to discuss some issues.

1. Should the menu stay open while selecting options? Maybe it is a good idea to make it configurable. If yes: Do we need a close button, or is it just fine to close the menu (which triggers the change)
2. Do we need a max value for selected items to show up in label? `Max:3 -> Chicken, Ant, Dog, ...`
3. Should we update the label while selecting? 
4. How to deal with the LabelBuilder?
5. How to deal with detectItemVisibility? Disabled for multiple?

I'm looking forward to your feedback :)

![mockup](https://cloud.githubusercontent.com/assets/965069/18625271/ca075368-7e4d-11e6-98a6-639768be9644.gif)

**Comment by manuelbieh** [comment]
1. It would not make sense to close it once you select an option since you explicitly allow or even want the user to select multiple entries. How annoying would it be to open the same dropdown 4 times if you want to select 4 options? ;)

2. Would definitely be a nice feature to have. 

4. Maybe you can make it configurable? `firstItemDisabled` true/false?

**Comment by gearsdigital** [comment]
1. Yeah, I thought the same and probably it would me drive nuts but here are some gotchas:
 - The change event is fired right after the user clicks on list item. What should we do, if a form submit is bound to the change event?
 - The label is updated, once the dropdown closes. A user might expect that his actual selection is reflected by the label, don't you think so?

2. Indeed!

3. I'm not a friend of "configure what could be configured".  Not sure about that, but maybe the way to go.

**Comment by manuelbieh** [comment]
… another way to disable selecting the frist item is to just add the `disabled` attribute to the first option.

**Comment by manuelbieh** [comment]
And to answer your question:
> What should we do, if a form submit is bound to the change event?

That's the developer's problem. Don't bind a change event to a `select` element with the `mutliple` present. Or at least not a form submitting change event handler :wink:

**Comment by gearsdigital** [comment]
> … another way to disable selecting the frist item is to just add the disabled attribute to the first option.

But should we take care about this or is it a developers problem too?

> What should we do, if a form submit is bound to the change event?

Okay, I'll ignore that.

**Comment by gearsdigital** [comment]
### Default Option Handling

```html
<select name="animals" multiple>
    <option disabled>Please choose...</option>
    <option value="ant">Ant</option>
    <option value="cat">Cat</option>
    <option value="dog">Dog</option>
    <option value="chicken">Chicken</option>
</select>
```

#### Result
![placeholder](https://cloud.githubusercontent.com/assets/965069/18638322/f6e17322-7e8f-11e6-84c9-1b6ef0d0b51f.gif)

- selected options are taken into account
- label builder are taken into account
- if no default option is given, browser default is used -> first option (or first selected option)
- default option can have a empty value

**Comment by gearsdigital** [comment]
[Fixed 3.](https://github.com/lcdsantos/jQuery-Selectric/issues/80#issuecomment-247930929).
> How to deal with detectItemVisibility? Disabled for multiple? Or use the first/last match to calculate visibility? 

It scrolls now to the uppermost selected item.

**Comment by gearsdigital** [comment]
Could be closed, too, right?
