### ISSUE TITLE
Get (not set) selectedIndex?

### ISSUE THREAD

**Issue by dsmithdewarcom** [lcdsantos/jQuery-Selectric#81]
Hi,

Please forgive me if I've overlooked this in the documentation, but how do I get selectedIndex? I've tried various iterations of $('#myid').selectedIndex but no joy. This is supposed to work on select elements in 'plain' javascript, so I asume the syntax is changed in selectric?

Thanks!

SOLVED: Needed bracket thingie: $('#myid')[0].selectedIndex (which was not in 'generic' js docs I previously reviewed).
Found here:
http://stackoverflow.com/questions/13556941/get-index-of-selected-option-with-jquery

**Comment by lcdsantos** [comment]
You can also use the jQuery [.prop()](http://api.jquery.com/prop/) method:
```js
$('#myid').prop('selectedIndex');
```
