### ISSUE TITLE
Can't enable / disable select by clicking checkbox

### ISSUE THREAD

**Issue by Nicero** [lcdsantos/jQuery-Selectric#83]
I'm not able to enable or disable a certain select box by checking or unchecking a checkbox. I noticed that **if I remove the line ```$('select').selectric();```, the following code works fine. If the plugin is initialized, the code doesn't work**. 

    <div class="labels-chk">
        <input type="checkbox" id="chk2" class="css-checkbox" name="Message">
        <label for="chk2" class="css-label">Show notification message&nbsp;</label>
    </div>

    <select id="select-warnings" disabled>
        <option value="load">as soon as page has loaded</option>
        <option value="date">on date</option>
    </select>

    <script type="text/javascript">
        $(document).ready(function(){
				
            $('select').selectric();

            $("#chk2").click(function() {
                var checked_status = this.checked;
                if (checked_status == true) {
                    $("#select-warnings").removeAttr("disabled");
                } else {
                    $("#select-warnings").attr("disabled", "disabled");
                }
            });
         });
    </script>

**Comment by Nicero** [comment]
Ok, I got it! Selectric has to be **refreshed**.

Change:
        ```$("#select-warnings").removeAttr("disabled");```
and
        ```$("#select-warnings").attr("disabled", "disabled");```

To:
        ```$("#select-warnings").removeAttr("disabled").selectric('refresh');```
and
        ```$("#select-warnings").attr("disabled", "disabled").selectric('refresh');```

**Comment by ianwhiteley** [comment]
Hi,

I and enabling / disabling selections (of the same name) depending on another selection. I do the above - but my second selectric input list is still "hidden" even after enabling. 

I tried the 'refresh' but that that just adds extra "empty" inputs to the screen. I am so confused. Disabling selectric everything works - but if I can't find a fix will look for an alternative.
