### ISSUE TITLE
How to use disableOnMobile: false but retain mobile drop down functionality?

### ISSUE THREAD

**Issue by deshg** [lcdsantos/jQuery-Selectric#90]
Hey, thanks for the great plugin! Just one query is it possible to set disableOnMobile: false so the select boxes are visually styled correctly on mobile but have them use the native mobile dropdown functionality? We can obviously use disableOnMobile: true but this means the actual select box has default styling as well which doesn't look great?

Thanks!

Dave

**Comment by rimbaudhotel** [comment]
I would like to know how to do this as well. I think this would be a great feature - Is this possible?

**Comment by Helgajijka** [comment]
I have the same problem(  did you manage to solve it?

**Comment by 14nd90** [comment]
+1 Would be very useful to have this implemented

**Comment by whythecode** [comment]
+1

**Comment by gearsdigital** [comment]
@lcdsantos I can implement this feature. I find it useful too, and it should not be that much work.
