### ISSUE TITLE
I need to be able to click disabled options

### ISSUE THREAD

**Issue by ChrisPlaneta** [lcdsantos/jQuery-Selectric#96]
I'm working on an e-commerce theme where selectric is used to display (among other things) lists od product variations. The idea is that when a user clicks a variation that is unavailable, a modal wil show up with a an "instock reminder" form so that a user will be notified when this variation will be available again.

At the moment I targeting disabled elements won't do anything and I'm not as good in jQuery/Javascript to be able to modify your script myself so that it can let me click the disabeld element.

Can you tell me what should i modify in your script so that I can do this?

Have a nice day,
Chris

**Comment by ChrisPlaneta** [comment]
OK, I've found a temporary solution. After lines.
'''if ( !_this.items[index].disabled ) {
            // If 'close' is false (default), the options box won't close after
            // each selected item, this is necessary for keyboard navigation
            $li
              .removeClass('selected')
              .eq(selected = index)
              .addClass('selected');

            _detectItemVisibility(index);
            close && _close();
          }
'''
I've added a simple code to my modal popup
''''
if ( _this.items[index].disabled ) {
    showPopup('qqProductNoticePopup');
}
'''

**Comment by lcdsantos** [comment]
It's possible to do like this now:

```js
$('select').on('selectric-before-select', function(event, element, scope, index) {
  if ( scope.items[index].disabled ) {
    // do something if element is disabled
  }
});
```
