### ISSUE TITLE
close on document click.sl event

### ISSUE THREAD

**Issue by minimihi** [lcdsantos/jQuery-Selectric#98]
I added custom scrollbar for selectric items list.
But selectric binds `click.sl` event on `document` element. Whitch perofrms call to `_close()`.

Checking whether `click.sl` is perforemed inside on selectric containers saves a day.

My walkaround looks like this:
```
            // Give dummy input focus
            $input.val('').is(':focus') || $input.focus();

-            $doc.on('click' + bindSufix, _close).on('scroll' + bindSufix, _isInViewport);
+            $doc.on('click' + bindSufix, function(event) {
+              if (event && event.target && ($(event.target).closest('.' + _this.classes.items).length || $(event.target).is('html'))) {
+                return false;
+              }
+              _close();
+            }).on('scroll' + bindSufix, _isInViewport);
            _isInViewport();
```

For me it looks good enough, but I noticed that `_close()` also performs selected value change on original SELECT element (?). It leaves me wondering why it is there.

**Comment by mcaskill** [comment]
I've applied this fix to my fork of Selectric.

Regarding your second observation (about the `_close()` selecting a new value), I've noticed that as well and have [fixed it](https://github.com/mcaskill/jQuery-Selectric/commit/480eeacee7f40d50c989c2c72000dfb755f33f8d)—to match the behaviour of native `<select>` elements.
