### ISSUE TITLE
autofill doesn't work

### ISSUE THREAD

**Issue by withintheruins14** [lcdsantos/jQuery-Selectric#99]
I am collecting each users address and using a select field to collect each users state. Before I apply Selectric, I have a select field that can successfully collect the users state when the browser autofills the form. After I call `<script>$(function(){ $('select').selectric();});</script>`, the browsers autofill feature stops working. It doesn't autocomplete the users state. I think Selectric is breaking the browsers autofill feature. Does anyone know a way to fix this?

**Comment by lcdsantos** [comment]
I think it's because the <select> element have a `display: none;`.

See if this works:
http://jsbin.com/xeqiki/edit?html,css,console,output

I've added `display: block;` to the select, and added a change event.

**Comment by withintheruins14** [comment]
Thanks @lcdsantos, this fixed things for me. My next issue is that Selectric() adds a tabindex of 0 to the original element. I need to skip past the original when tabbing and I want it to have a tabindex of -1. I doing so now with `$('select').attr('tabindex', '-1');` after I have called selectric(). Do you know a way of doing this as well? Thanks for your help!
